# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96edbfbd518d29fdec4b594aa7ebd104477e245feaea89f582d095fa6f893c8e28782bd92f6f559882f5c7e99d80489dfa81cb22ccc02d2f2c386743c91e613d

test:
  secret_key_base: 52d442119b5986360aa6c845cad717163bb0ab9165ced0144a7a0f11d92f954f29061eb6d880e6ad6470d9412b5134ee700b0e48033dcb3bf2c94d3aecf79d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
